blackbox_exporter/blackbox_exporter.spec
the icmp prober need the capability cap_net_raw.
=> Set cap_net_raw for blackbox_exporter binary.

prometheus2/prometheus.default, prometheus2/prometheus.service, prometheus2/prometheus2.spec
It will be better to have these keys in `/etc/default/prometheus` for easier maintenance. In case you want to customize these options you will have to remove/modify them in `/usr/lib/systemd/system/prometheus.service`. 
If you'll put one of the in defaults, prometheus will fail to start with: `Error parsing commandline arguments: flag 'xxxxxxx' cannot be repeated`
=> Changed location of configuration keys.

alertmanager/alertmanager.spec, apache_exporter/apache_exporter.spec, blackbox_exporter/blackbox_exporter.spec, collectd_exporter/collectd_exporter.spec, consul_exporter/consul_exporter.spec, elasticsearch_exporter/elasticsearch_exporter.spec, graphite_exporter/graphite_exporter.spec, haproxy_exporter/haproxy_exporter.spec, jmx_exporter/jmx_exporter.spec, mysqld_exporter/mysqld_exporter.spec, node_exporter/node_exporter.spec, postgres_exporter/postgres_exporter.spec, prometheus/prometheus.spec, prometheus2/prometheus2.spec, pushgateway/pushgateway.spec, rabbitmq_exporter/rabbitmq_exporter.spec, redis_exporter/redis_exporter.spec, sachet/sachet.spec, snmp_exporter/snmp_exporter.spec, statsd_exporter/statsd_exporter.spec
This uses RPM macros (https://fedoraproject.org/wiki/Packaging:RPMMacros) for common locations. It also uses install -D which removes the need for mkdir -p.
=> Use RPM macros and install -D

rabbitmq_exporter/rabbitmq_exporter.spec
Descriptions of the changes in each release:
- https://github.com/kbudde/rabbitmq_exporter/releases/tag/v0.27.0
- https://github.com/kbudde/rabbitmq_exporter/releases/tag/v0.27.1
- https://github.com/kbudde/rabbitmq_exporter/releases/tag/v0.28.0
=> Bump rabbitmq_exporter from 0.26.0 to 0.28.0

README.md
Improves documentation showing installation methods for CentOS 6 as well as 7 and add some help for adding a new exporter.
=> improve documentation for auto generated

alertmanager/alertmanager.spec, haproxy_exporter/haproxy_exporter.spec, prometheus2/prometheus2.spec, pushgateway/pushgateway.spec, snmp_exporter/snmp_exporter.spec
Bumped the version of several components - someone already has a PR open for mysqld_exporter #55 .
Not sure if the summary for prometheus2.spec should just be "The Prometheus 2 monitoring system and time series database." instead of including the exact version, but that's what was there already.
=> updated version of several components

sachet/sachet.spec
I assume that changing the version number in sachet.spec is what it takes to use a newer version?
That's how it was done here:
https://github.com/lest/prometheus-rpm/pull/56/commits/fbb06bbf6a1a6486d1713c0d65cd250261a300da
=> sachet version 0.0.8

postgres_exporter/postgres_exporter.spec, templating.yaml
Bump postgres exporter version to 0.4.7 to support postgres 11 (support 'B' suffix in units)
=> Bump postgres exporter version to 0.4.7

templates/init.tpl
Fix to typo in generated initd entry:  "retart" => "restart". Found on Centos6 node_exporter build.
=> Fix to initd restart

sachet/sachet.spec
There have been plenty of new sachet versions since 0.0.8
=> sachet version 0.2.0

prometheus2/prometheus2.spec
Bumping Prometheus version to 2.6.0, released on 2018-12-17
=> Update prometheus2.spec to 2.6.0

templates/init.tpl
* Support running as prometheus user (via USER=  added to /etc/defaults by end user)
* Fix "service node_exporter restart" bug on el6  - $USER  needs to be set
* Keep everything running as root by default
=> Allow node_exporter (and others) to be run as non root

alertmanager/alertmanager.spec
builds ok on el7:
$make alertmanager
...
Wrote: /rpmbuild/RPMS/x86_64/alertmanager-0.16.0-1.el7.centos.x86_64.rpm
...
=> Add alertmanager 0.16.0

blackbox_exporter/blackbox_exporter.spec
From the release announcement:
I've just released version 0.14.0 of the blackbox exporter. If you're using HTTP body regex matching, you'll need to update the name of the field in the config file:
[CHANGE] fail_if_matches_regexp is now fail_if_body_matches_regexp in config file (#419)
[FEATURE] Add regexp matching of HTTP response headers to the http probe (#419)
[FEATURE] Add config option to disable protocol fallback (#382)
[ENHANCEMENT] Add Last-Modified HTTP header metric (#407)
[ENHANCEMENT] Add metrics for successful config loading (#413)
[BUGFIX] prober: icmp: Initialize ID and sequence to random values (#412)
=> blackbox_exporter version bump

templating.yaml
Request to rebuild node_exporter rpms to pull in initd fixes since last bump in version (Nov2018).
=> new release -2 of node_exporter to pull in initd fixes

prometheus2/prometheus2.spec
Prometheus 2.9.2 released:
[BUGFIX] Make sure subquery range is taken into account for selection #5467
[BUGFIX] Exhaust every request body before closing it #5166
[BUGFIX] Cmd/promtool: return errors from rule evaluations #5483
[BUGFIX] Remote Storage: string interner should not panic in release #5487
[BUGFIX] Fix memory allocation regression in mergedPostings.Seek tsdb#586
I'm also proposing changing the summary to just 'Prometheus 2.x', so we don't have to keep updating it
=> Bumping Prometheus to 2.9.2

pushgateway/pushgateway.spec
[CHANGE] Run as user nobody in Docker. #242
[CHANGE] Adjust --web.route-prefix to work the same as in Prometheus. #190
[FEATURE] Add --web.external-url flag (like in Prometheus). #190
=> Update Pushgateway to 0.8.0

Makefile, thanos/thanos-compact.default, thanos/thanos-compact.service, thanos/thanos-query.default, thanos/thanos-query.service, thanos/thanos-sidecar.default, thanos/thanos-sidecar.service, thanos/thanos-store.default, thanos/thanos-store.service, thanos/thanos.spec
Add Thanos RPM package:
https://improbable.io/blog/thanos-prometheus-at-scale
Note: I have disabled clustering (`--cluster.disable`) in service defaults as this feature will shortly be deprecated and is already disabled by default in upcoming Thanos version 0.4.x, thus it doesn't make much sense to rely on this feature on new deployments.
=> Initial version of Thanos RPM package.

templating.yaml
Rel. 0.18.0
https://github.com/prometheus/node_exporter/releases/tag/v0.18.0
Breaking changes
Renamed interface label to device in netclass collector for consistency with
other network metrics #1224
The cpufreq metrics now separate the cpufreq and scaling data based on what the driver provides. #1248
The labels for the network_up metric have changed, see issue #1236
Bonding collector now uses mii_status instead of operstatus #1124
Several systemd metrics have been turned off by default to improve performance #1254
These include unit_tasks_current, unit_tasks_max, service_restart_total, and unit_start_time_seconds
The systemd collector blacklist now includes automount, device, mount, and slice units by default. #1255
Changes
[CHANGE] Bonding state uses mii_status #1124
[CHANGE] Add a limit …
=> node_exporter version bump

templating.yaml
Changes
[BUGFIX] Fix incorrect sysctl call in BSD meminfo collector, resulting in broken swap metrics on FreeBSD #1345
[BUGFIX] Fix rollover bug in mountstats collector #1364
=> Update node_exporter to 0.18.1

thanos/thanos-compact.default, thanos/thanos-compact.service, thanos/thanos-query.default, thanos/thanos-rule.default, thanos/thanos-rule.service, thanos/thanos-sidecar.default, thanos/thanos-sidecar.service, thanos/thanos-store.default, thanos/thanos-store.service
tsdb.path needs to be in defaults so it can be overridden - otherwise you will get:
Error parsing commandline arguments: flag 'tsdb.path' cannot be repeated
=> thanos sidecar: move tsdb.path to defaults so it can be overridden

thanos/thanos.spec
Fixed
#1142 fixed major leak on store LRU cache for index items (postings and series).
#1163 sidecar is no longer blocking for custom Prometheus versions/builds. It only checks if flags return non 404, then it performs optional checks.
#1146 store/bucket: make getFor() work with interleaved resolutions.
#1157 querier correctly handles duplicated stores when some store changes external labels in place.
Added
#1094 Allow configuring the response header timeout for the S3 client.
Changed
#1118 breaking swift: Added support for cross-domain authentication by introducing userDomainID, userDomainName, projectDomainID, projectDomainName.
The outdated terms tenantID, tenantName are deprecated and have been replaced by projectID, projectName.
#1066 Upgrade Thanos ui to Prometheus v2.9.1.
Changes …
=> Update Thanos to 0.5.0

postgres_exporter/postgres_exporter.spec
Release notes:
* Docker image now runs as a non-root user named "postgres_exporter"
* Add `--auto-discover-databases` option, which automatically discovers and scrapes all databases.
* Add support for boolean data types as metrics
* Replication lag is now expressed as a float and not truncated to an integer.
* When default metrics are disabled, no version metrics are collected anymore either.
* BUGFIX: Fix exporter panic when postgres server goes down.
* Add support for collecting metrics from multiple servers.
* PostgreSQL 11 is now supported in the integration tests.
=> Update postgres expoter to 0.5.0

alertmanager/alertmanager.spec
[CHANGE] Remove quantile labels from Summary metrics. #1921
[CHANGE] [OpsGenie] Move from the deprecated teams field in the configuration to responders. #1863
[CHANGE] [ui] Collapse alert groups on the initial view. #1876
[CHANGE] [Wechat] Set the default API secret to blank. #1888
[CHANGE/BUGFIX] [PagerDuty] Fix embedding of images, the text field in the configuration has been renamed to href. #1931
[ENHANCEMENT] Use persistent HTTP clients. #1904
[ENHANCEMENT] Add alertmanager_cluster_alive_messages_total, alertmanager_cluster_peer_info and alertmanager_cluster_pings_seconds metrics. #1941
[ENHANCEMENT] [api] Add missing metrics for API v2. #1902
[ENHANCEMENT] [Slack] Log error message on retry errors. #1655
[ENHANCEMENT] [ui] Allow to create silences from the alerts filter bar. #1911 …
=> Update Alertmanager to 0.18.0

prometheus2/prometheus2.spec
[CHANGE] Remove max_retries from queue_config (it has been unused since rewriting remote-write to utilize the write-ahead-log). #5649
[CHANGE] The meta file BlockStats no longer holds size information. This is now dynamically calculated and kept in memory. It also includes the meta file size which was not included before. tsdb#637
[CHANGE] Renamed metric from prometheus_tsdb_wal_reader_corruption_errors to prometheus_tsdb_wal_reader_corruption_errors_total. tsdb#622
[FEATURE] Add option to use Alertmanager API v2. #5482
[FEATURE] Added humanizePercentage function for templates. #5670
[FEATURE] Include InitContainers in Kubernetes Service Discovery. #5598
[FEATURE] Provide option to compress WAL records using Snappy. #609
[ENHANCEMENT] Create new clean segment when starting the WAL. …
=> Update Prometheus to 2.11.0

prometheus2/prometheus2.spec
Point release:
[BUGFIX] Fix potential panic when prometheus is watching multiple zookeeper paths. #5749
=> Prometheus 2.11.1

thanos/thanos.spec
Added
#1097 Added thanos check rules linter for Thanos rule rules files.
#1253 Add support for specifying a maximum amount of retries when using Azure Blob storage (default: no retries).
#1244 Thanos Compact now exposes new metrics thanos_compact_downsample_total and thanos_compact_downsample_failures_total which are useful to catch when errors happen
#1260 Thanos Query/Rule now exposes metrics thanos_querier_store_apis_dns_provider_results and thanos_ruler_query_apis_dns_provider_results which tell how many addresses were configured and how many were actually discovered respectively
#1248 Add a web UI to show the state of remote storage.
#1217 Thanos Receive gained basic hashring support
#1262 Thanos Receive got a new metric thanos_http_requests_total which shows how many requests were …
=> Update to Thanos 0.6.0

pushgateway/pushgateway.spec
---
0.9.0 / 2019-07-23
[CHANGE] Web: Update to Bootstrap 4.3.1 and jquery 3.4.1, changing appearance of the web UI to be more in line with the Prometheus server. Also add favicon and remove timestamp column. #261
[CHANGE] Update logging to be in line with other Prometheus projects, using gokit and promlog. #263
[FEATURE] Add optional base64 encoding for label values in the grouping key. #268
[FEATURE] Add ARM container images. #265
[FEATURE] Log errors during scrapes. #267
[BUGFIX] Web: Fixed Content-Type for js and css instead of using /etc/mime.types. #252
=> pushgateway version bump

pushgateway/pushgateway.spec
Upstream bugfix release:
---
[BUGFIX] Make --web.external-url and --web.route-prefix work as documented. #274
=> Pushgateway version bump - 0.9.1

postgres_exporter/postgres_exporter.spec
Changes:
- Add application_name as a label for pg_stat_replication metrics (#285).
=> Update Postgres exporter to 0.5.1

thanos/thanos.spec
v0.7.0
Accepted into CNCF:
Thanos moved to new repository https://github.com/thanos-io/thanos
Docker images moved to https://quay.io/thanos/thanos and mirrored at https://hub.docker.com/r/thanosio/thanos
Slack moved to https://slack.cncf.io #thanos/#thanos-dev / #thanos-prs
Added
#1378 Thanos Receive now exposes thanos_receive_config_hash, thanos_receive_config_last_reload_successful and thanos_receive_config_last_reload_success_timestamp_seconds metrics to track latest configuration change
#1268 Thanos Sidecar added support for newest Prometheus streaming remote read added here. This massively improves memory required by single
request for both Prometheus and sidecar. Single requests now should take constant amount of memory on sidecar, so resource consumption prediction is now …
=> Update Thanos to 0.7.0

generate.py
I was tearing my hair out on this one - after my (minor) PR to clean up the autogen_* files with 'make clean', I was getting random build failures.  Turns out the old autogen_* files laying around were concealing a bug.
I eventually figured out the issue was the ordering of the 'dynamic' sections - as the comment says, 'dynamic contexts can use other dynamic contexts as long as they are compiled before' - 'sources' uses 'tarball', but processing order was random.
I've updated it to always process 'tarball' then 'sources'.
The drawback is that we can't add other 'dynamic' contexts w/o a code change, but only the postgres_exporter is overriding the default & that's just setting 'tarball' (and it looks like it doesn't even need to do that).
I also thought about just doing a reverse sort of …
=> specify order of dynamic context sections

alertmanager/alertmanager.spec
---
CHANGE] Reject invalid external URLs at startup. #1960
[CHANGE] Add Fingerprint to template data. #1945
[CHANGE] Check Smarthost validity at config loading. #1957
[ENHANCEMENT] Improve error messages for email receiver. #1953
[ENHANCEMENT] Log error messages from OpsGenie API. #1965
[ENHANCEMENT] Add the ability to configure Slack markdown field. #1967
[ENHANCEMENT] Log warning when repeat_interval > retention. #1993
[ENHANCEMENT] Add alertmanager_cluster_enabled metric. #1973
[ENHANCEMENT] [ui] Recreate silence with previous comment. #1927
[BUGFIX] [ui] Fix /api/v2/alerts/groups endpoint with similar alert groups. #1964
[BUGFIX] Allow slashes in receivers. #2011
[BUGFIX] [ui] Fix expand/collapse button with identical alert groups. #2012
=> Bump Alertmanager version

blackbox_exporter/blackbox_exporter.spec
---
[FEATURE] Adding web.external-url and web.route-prefix flags (#515)
[ENHANCEMENT] Bump default timeout to 2m (#509)
[ENHANCEMENT] Use HTTP request's context, so cancellation works. (#510)
[ENHANCEMENT] Add separate history for expired failed probe results (#517)
[BUGFIX] Handle SIGTERM gracefully (#449)
[BUGFIX] Close configuration file (#467)
[BUGFIX] Use timeout for chooseProtocol (#458)
[BUGFIX] Do not apply offsets for explicit timeouts (#492)
[BUGFIX] Don't put v4 addresses in brackets (#506)
[BUGFIX] Set TLSHandshakeTimeout in HTTP transport (common#179)
=> blackbox_exporter version bump to 0.15.0

blackbox_exporter/blackbox_exporter.spec
---
[BUGFIX] Fix probe log links on front page when route prefix is set (#520)
=> Bump blackbox_exporter - upstream release

Makefile, smokeping_prober/smokeping_prober.default, smokeping_prober/smokeping_prober.service, smokeping_prober/smokeping_prober.spec
Adding https://github.com/SuperQ/smokeping_prober
"This prober sends a series of ICMP (or UDP) pings to a target and records the responses in Prometheus histogram metrics."
=> adding smokeping_prober

thanos/thanos.spec
Added
#1619 Thanos sidecar allows to limit min time range for data it exposes from Prometheus.
#1583 Thanos sharding:
Add relabel config (--selector.relabel-config-file and selector.relabel-config) into Thanos Store and Compact components.
Selecting blocks to serve depends on the result of block labels relabeling.
For store gateway, advertise labels from "approved" blocks.
#1540 Thanos Downsample added /-/ready and /-/healthy endpoints.
#1538 Thanos Rule added /-/ready and /-/healthy endpoints.
#1537 Thanos Receive added /-/ready and /-/healthy endpoints.
#1460 Thanos Store Added /-/ready and /-/healthy endpoints.
#1534 Thanos Query Added /-/ready and /-/healthy endpoints.
#1533 Thanos inspect now supports the timeout flag.
#1496 Thanos Receive now supports setting block duration.
#1362 …
=> Update to Thanos 0.8.0

alertmanager/alertmanager.service, alertmanager/alertmanager.spec, blackbox_exporter/blackbox_exporter.service, blackbox_exporter/blackbox_exporter.spec, prometheus2/prometheus.service, prometheus2/prometheus2.spec, snmp_exporter/snmp_exporter.service, snmp_exporter/snmp_exporter.spec
Bump LimitNOFILE to 65536 for the following packages:
- prometheus2
- alertmanager
- blackbox_exporter
- snmp_exporter
cc: @karlism 
re: #144
=> set LimitNOFILE to 65536 for some services

thanos/thanos.spec
Fixed
#1632 Removes the duplicated external labels detection on Thanos Querier. It is warning only now. Also made Store Gateway compatible with older Querier versions.
NOTE: thanos_store_nodes_grpc_connections metric is now per external_labels and store_type. It is a recommended metric for Querier storeAPIs. thanos_store_node_info is marked as obsolete and will be removed in next release.
NOTE2: Store Gateway is now advertising artificial: "@thanos_compatibility_store_type=store" label. This is to have the current Store Gateway compatible with Querier pre v0.8.0.
This label can be disabled by hidden debug.advertise-compatibility-label=false flag on Store Gateway.
=> Update to Thanos 0.8.1

postgres_exporter/postgres_exporter.spec
v0.6.0
* Add SQL for grant connect (#303)
* Expose pg_current_wal_lsn_bytes (#307)
* [minor] fix landing page content-type (#305)
* Updated lib/pg driver to 1.2.0 in order to support stronger SCRAM-SHA-256 authentication. This drops support for Go < 1.11 and PostgreSQL < 9.4. (#304)
* Provide more helpful default values for tables that have never been vacuumed (#310)
* Add retries to getServer() (#316)
* Fix pg_up metric returns last calculated value without explicit resetting (#291)
* Discover only databases that are not templates and allow connections (#297)
* Add --exclude-databases option (#298)
v0.7.0
Introduces some more significant changes, hence the minor version bump in
such a short time frame.
* Rename pg_database_size to pg_database_size_bytes in queries.yml.
* Add …
=> Update Posgres Exporter to 0.7.0

blackbox_exporter/blackbox_exporter.spec
Upstream release 0.16.0
---
* [ENHANCEMENT] Add probe_http_uncompressed_body_length metric (#535)
* [ENHANCEMENT] Export TLS version (#538)
* [BUGFIX] Better handling of HTTP redirects. (#530)
* [BUGFIX] Fix logging of IP addresseses in resolve code. (#548)
=> Upstream blackbox_exporter release - 0.16.0

postgres_exporter/postgres_exporter.spec
* Add a build info metric (#323)
* Re-add pg_stat_bgwriter metrics which were accidentally removed in the previous version. (resolves #336)
* Export pg_stat_archiver metrics (#324)
* Add support for 'DATA_SOURCE_URI_FILE' envvar.
* Resolve #329
* Added new field "master" to queries.yaml. (credit to @sfalkon)
- If "master" is true, query will be call only on once database in instance
* Change queries.yaml for work with autoDiscoveryDatabases options (credit to @sfalkon)
- added current database name to metrics because any database in cluster maybe have the same table names
- added "master" field for query instance metrics.
=> Update postgres exporter to 0.8.0

snmp_exporter/snmp_exporter.spec
[FEATURE] Support BITS values. (#465)
[ENHANCEMENT] Add option to fail on parse errors in the generator. (#382)
[ENHANCEMENT] Switch logging to go-kit (#447)
[BUGFIX] Handle trailing linefeed in NetSNMP output adding 1 to the error count (#398)
=> Update SNMP exporter to 0.16.1

thanos/thanos.spec
Added:
#1678 Add Lightstep as a tracing provider.
#1687 Add a new --grpc-grace-period CLI option to components which serve gRPC to set how long to wait until gRPC Server shuts down.
#1660 Sidecar: Add a new --prometheus.ready_timeout CLI option to the sidecar to set how long to wait until Prometheus starts up.
#1573 AliYun OSS object storage, see documents for further information.
#1680 Add a new --http-grace-period CLI option to components which serve HTTP to set how long to wait until HTTP Server shuts down.
#1712 Bucket: Rename flag on bucket web component from --listen to --http-address to match other components.
#1733 Compactor: New metric thanos_compactor_iterations_total on Thanos Compactor which shows the number of successful iterations.
#1758 Bucket: thanos bucket web now …
=> Update to Thanos 0.9.0

statsd_exporter/statsd_exporter.spec
New upstream release - 0.13.0
We've missed a bunch - some breaking changes in here:
0.13.0 / 2019-12-06
[ENHANCEMENT] Support sampling factors for all statsd metric types (#264)
[ENHANCEMENT] Support Librato and InfluxDB labeling formats (#267)
0.12.2 / 2019-07-25
[BUGFIX] Fix Unix socket handler (#252)
[BUGFIX] Fix panic under high load (#253)
Thank you to everyone who reported and helped debug these issues!
0.12.1 / 2019-07-08
[BUGFIX] Renew TTL when a metric receives updates (#246)
[CHANGE] Reload on SIGHUP instead of watching the file (#243)
0.11.2 / 2019-06-14
[BUGFIX] Fix TCP handler (#235)
0.11.1 / 2019-06-14
[ENHANCEMENT] Batch event processing for improved ingestion performance (#227)
[ENHANCEMENT] Switch Prometheus client to promhttp, freeing the standard HTTP metrics (#233) …
=> version bump of statsd_exporter

prometheus2/prometheus2.spec
[CHANGE] Discovery: Removed prometheus_sd_kubernetes_cache_* metrics. Additionally prometheus_sd_kubernetes_workqueue_latency_seconds and prometheus_sd_kubernetes_workqueue_work_duration_seconds metrics now show correct values in seconds. #6393
[CHANGE] Remote write: Changed query label on prometheus_remote_storage_* metrics to remote_name and url. #6043
[FEATURE] API: Added new endpoint for exposing per metric metadata /metadata. #6420 #6442
[ENHANCEMENT] TSDB: Significantly reduced memory footprint of loaded TSDB blocks. #6418 #6461
[ENHANCEMENT] TSDB: Significantly optimized what we buffer during compaction which should result in lower memory footprint during compaction. #6422 #6452 #6468 #6475
[ENHANCEMENT] TSDB: Improve replay latency. #6230
[ENHANCEMENT] TSDB: WAL size is now used …
=> Update to Prometheus 2.15.0

thanos/thanos.spec
Fixed
#1919 Compactor: Fixed potential data loss when uploading older blocks, or upload taking long time while compactor is
running.
#1937 Compactor: Improved synchronization of meta JSON files.
Compactor now properly handles partial block uploads for all operation like retention apply, downsampling and compaction. Additionally:
Removed thanos_compact_sync_meta_* metrics. Use thanos_blocks_meta_* metrics instead.
Added thanos_consistency_delay_seconds and thanos_compactor_aborted_partial_uploads_deletion_attempts_total metrics.
#1936 Store: Improved synchronization of meta JSON files. Store now properly handles corrupted disk cache. Added meta.json sync metrics.
#1856 Receive: close DBReadOnly after flushing to fix a memory leak.
#1882 Receive: upload to object storage as 'receive' rather …
=> Update to Thanos 0.10.0.

statsd_exporter/statsd_exporter.spec
0.14.1 released:
[BUGFIX] Mapper cache poisoning when name is variable (#286)
[BUGFIX] nil pointer dereference in UDP listener (#287)
[CHANGE] Switch logging to go-kit (#283)
[CHANGE] Rename existing metric for mapping cache size (#284)
[ENHANCEMENT] Add metrics for mapping cache hits (#280)
=> statsd_exporter upstream release

thanos/thanos.spec
10.0.1
---
Fixed
#2015 Sidecar: Querier /api/v1/series bug fixed when time range was ignored inside sidecar. The bug was noticeable for example when using Grafana template variables.
=> Thanos - upstream release

pushgateway/pushgateway.spec
---
It adds a new flag --push.disable-consistency-check, which can be used to disable the push-time checks introduced in v0.10. Using this flag is dangerous because it will allow pushing metrics that lead to an inconsistent state of the metrics served by the Pushgateway. After pushing a metric that leads to such inconsistencies, the whole Pushgateway will fail scrapes by Prometheus until the offending metrics are deleted. However, the push-time check has a performance cost, and thus disabling it is required in situations where pushes happen very frequently and the Pushgateway has to store a lot of metrics. Arguably, those situations only happen when the Pushgateway is used in ways it is not intended for (cf. the documented best practices). However, to not break the usage …
=> pushgateway - upstream release

graphite_exporter/graphite_exporter.spec
---
0.7.0 / 2020-02-28
@prombot prombot released this 1 hour ago
[CHANGE] Update logging library and flags (#109)
[CHANGE] Updated prometheus golang client and statsd mapper dependency. (#113)
This release updates several dependencies. Logging-related flags have changed.
The metric mapping library is now at the level of statsd exporter 0.14.1, bringing in various performance improvements. See the statsd exporter changelog for the detailed changes.
=> graphite_exporter upstream release - 0.7.0

thanos/thanos.spec
Fixed
#2033 Minio-go: Fixed Issue #1494 support Web Identity providers for IAM credentials for AWS EKS.
#1985 Store Gateway: Fixed case where series entry is larger than 64KB in index.
#2051 Ruler: Fixed issue where ruler does not expose shipper metrics.
#2101 Ruler: Fixed bug where thanos_alert_sender_errors_total was not registered.
#1789 Store Gateway: Improve timeouts.
#2139 Properly handle SIGHUP for reloading.
#2040 UI: Fix URL of alerts in Ruler
#2033 Ruler: Fix tracing in Thanos Ruler
Added
#2003 Query: Support downsampling for /series.
#1952 Store Gateway: Implemented binary index header. This significantly reduces resource consumption (memory, CPU, net bandwidth) for startup and data loading processes as well as baseline memory. This means that adding more blocks into object …
=> Update to Thanos 0.11.0

statsd_exporter/statsd_exporter.spec
https://github.com/prometheus/statsd_exporter/releases/tag/v0.15.0
---
[ENHANCEMENT] Allow setting granularity for summary metrics (#290)
[ENHANCEMENT] Support a random-replacement cache invalidation strategy (#281
To facilitate the expanded settings for summaries, the configuration format changes from
mappings:
- match: …
timer_type: summary
quantiles:
- quantile: 0.99
error: 0.001
- quantile: 0.95
error: 0.01
…
to
mappings:
- match: …
timer_type: summary
summary_options:
quantiles:
- quantile: 0.99
error: 0.001
- quantile: 0.95
error: 0.01
…
max_summary_age: 30s
summary_age_buckets: 3
stream_buffer_size: 1000
…
For consistency, the format for histogram buckets also changes from
mappings:
- match: …
timer_type: histogram
buckets: [ 0.01, 0.025, 0.05, 0.1 ]
to
mappings: …
=> statsd_exporter upstream release - 0.15.0

prometheus2/prometheus2.spec
This release implements isolation in TSDB. API queries and recording rules are
guaranteed to only see full scrapes and full recording rules. This comes with a
certain overhead in resource usage. Depending on the situation, there might be
some increase in memory usage, CPU usage, or query latency.
[FEATURE] TSDB: Support isolation #6841
[ENHANCEMENT] PromQL: Allow more keywords as metric names #6933
[ENHANCEMENT] React UI: Add normalization of localhost URLs in targets page #6794
[ENHANCEMENT] Remote read: Read from remote storage concurrently #6770
[ENHANCEMENT] Rules: Mark deleted rule series as stale after a reload #6745
[ENHANCEMENT] Scrape: Log scrape append failures as debug rather than warn #6852
[ENHANCEMENT] TSDB: Improve query performance for queries that partially hit the head …
=> Update to Prometheus 2.17.0

thanos/thanos.spec
Fixed
#2288 Ruler: fixes issue #2281, a bug causing incorrect parsing of query address with path prefix.
#2238 Ruler: fixed issue #2204, where a bug in alert queue signaling filled up the queue and alerts were dropped.
#2231 Bucket Web: sort chunks by thanos.downsample.resolution for better grouping.
#2254 Bucket: fix issue where metrics were registered multiple times in bucket replicate.
#2271 Bucket Web: fixed issue #2260, where the bucket passes null when storage is empty.
#2339 Query: fix a bug where --store.unhealthy-timeout was never respected.
#2208 Query and Rule: fix handling of web.route-prefix to correctly handle / and prefixes that do not begin with a /.
#2311 Receive: ensure receive component serves TLS when TLS configuration is provided.
#2319 Query: fixed inconsistent …
=> Update Thanos to 0.12.0

prometheus2/prometheus2.spec
[BUGFIX] Federation: Register federation metrics #7081
[BUGFIX] PromQL: Fix panic in parser error handling #7132
[BUGFIX] Rules: Fix reloads hanging when deleting a rule group that is being evaluated #7138
[BUGFIX] TSDB: Fix a memory leak when prometheus starts with an empty TSDB WAL #7135
[BUGFIX] TSDB: Make isolation more robust to panics in web handlers #7129 #7136
=> Update Prometheus to 2.17.2

postgres_exporter/postgres_exporter.service, postgres_exporter/postgres_exporter.spec
Replacement for:
https://github.com/lest/prometheus-rpm/pull/209
https://github.com/lest/prometheus-rpm/pull/210
https://github.com/lest/prometheus-rpm/pull/211
Switches `postgres_exporter` to `postgres` system account so that it can connect to local PostgreSQL server instance.
=> Switch to postgres system account.

templating.yaml
Keepalived exporter requires to be run as root since it needs to send SIGUSR1 to `keepalived` process, which runs as root on CentOS
=> Switch keepalived exporter to root user

thanos/thanos.spec
Fixed
#2459 Compact: Fixed issue with old blocks being marked and deleted in a (slow) loop.
#2533 Rule: do not wrap reload endpoint with /. Makes /-/reload accessible again when no prefix has been specified.
=> Update Thanos to 0.12.2

prometheus2/prometheus2.spec
[CHANGE] Federation: Only use local TSDB for federation (ignore remote read). #7077
[CHANGE] Rules: rule_evaluations_total and rule_evaluation_failures_total have a rule_group label now. #7094
[FEATURE] Tracing: Added experimental Jaeger support #7148
[ENHANCEMENT] TSDB: Significantly reduce WAL size kept around after a block cut. #7098
[ENHANCEMENT] Discovery: Add architecture meta label for EC2. #7000
[BUGFIX] UI: Fixed wrong MinTime reported by /status. #7182
[BUGFIX] React UI: Fixed multiselect legend on OSX. #6880
[BUGFIX] Remote Write: Fixed blocked resharding edge case. #7122
[BUGFIX] Remote Write: Fixed remote write not updating on relabel configs change. #7073
=> Update to Prometheus 2.18.0

.travis.yml, Makefile, sachet/sachet.spec
Add CentOS 8 support for manual packages.
Update Sachet to 0.2.3 and remove `make` dependency.
Resolves https://github.com/lest/prometheus-rpm/issues/152
=> Add manual package CentOS 8 support

templating.yaml
Changelog
b7cdf62 update release process notes in README
c98cb10 cut 1.0.0 release
66ae153 add a grafana dashboard (#25)
13519dd add goreleaser
e3477cf add TLS version metric (#24)
80765ab add a github action to build the docker image
78ce406 fix tests
11e3e4c move metadata out of metrics and into labels
000c8a8 add tests for notBefore and notAfter
486b47f describe not before metric
0983ffd use the parsed target when connecting with the http client
874f02f fix docker instructions in README
5b927d8 fix example queries in README
81ff845 bump go version in .promu.yaml
0089529 build with go 1.13 explicitly in the Dockerfile
0a4a402 remove unnecessary STATICCHECK_IGNORE from Makefile
6d5223c use promhttp.Handler()
81504f6 make it work with Go 1.13
=> Update SSL exporter to 1.0.0

process_exporter/process_exporter.spec
Changelog:
f91ecbb PID and StartTime are now available as templates to use in defining a groupname.
=> Update Process Exporter to 0.6.0

templating.yaml
Breaking changes
The netdev collector CLI argument --collector.netdev.ignored-devices was renamed to --collector.netdev.device-blacklist in order to conform with the systemd collector. #1279
The label named state on node_systemd_service_restart_total metrics was changed to name to better describe the metric. #1393
Refactoring of the mdadm collector changes several metrics
node_md_disks_active is removed
node_md_disks now has a state label for "fail", "spare", "active" disks.
node_md_is_active is replaced by node_md_state with a state set of "active", "inactive", "recovering", "resync".
Additional label mountaddr added to NFS device metrics to distinguish mounts from the same URL, but different IP addresses. #1417
Metrics node_cpu_scaling_frequency_min_hrts and …
=> Update Node Exporter to 1.0.0

snmp_exporter/snmp_exporter.spec
[FEATURE] Allow lookup chaining in a basic way (#489)
[BUGFIX] Reduce and fix timeouts for SNMP requests (#511)
=> Update SNMP exporter to 0.18.0

consul_exporter/consul_exporter.spec
---
Simon Pasquier <pasquier.simon@gmail.com>
Jun 11, 2020, 8:42 AM (4 days ago)
to prometheus-announce
Hello all,
We're pleased to announce the release of consul_expoter v0.7.0 [1].
* [FEATURE] Add consul_service_checks metric to link checks with their
services. #162
* [ENHANCEMENT] Add --consul.request-limit flag to limit the maximum
number of concurrent requests to Consul. #164
=> Update consul_exporter - upstream release 0.7.0

templating.yaml
[BUGFIX] filesystem_freebsd: Fix label values #1728
[BUGFIX] Update prometheus/procfs to fix log noise #1735
[BUGFIX] Fix build tags for collectors #1745
[BUGFIX] Handle no data from powersupplyclass #1747, #1749
=> Update node exporter to 1.0.1

alertmanager/alertmanager.spec
This release removes the HipChat integration as it is discontinued by Atlassian on June 30th 2020.
[CHANGE] [HipChat] Remove HipChat integration as it is end-of-life. #2282
[CHANGE] [amtool] Remove default assignment of environment variables. #2161
[CHANGE] [PagerDuty] Enforce 512KB event size limit. #2225
[ENHANCEMENT] [amtool] Add cluster command to show cluster and peer statuses. #2256
[ENHANCEMENT] Add redirection from / to the routes prefix when it isn't empty. #2235
[ENHANCEMENT] [Webhook] Add max_alerts option to limit the number of alerts included in the payload. #2274
[ENHANCEMENT] Improve logs for API v2, notifications and clustering. #2177 #2188 #2260 #2261 #2273
[BUGFIX] Fix child routes not inheriting their parent route's grouping when group_by: [...]. #2154
[BUGFIX] [UI] Fix …
=> Update Alertmanager to 0.21.0

templating.yaml
Updating redis_exporter from 1.6.0 to 1.8.0
---
v1.8.0
PR #393 - Allow passing Root CA Cert file for TLS connections (thx @SarjakSShah )
v1.7.0
PR #392 - Add support for Redis 6 username auth (thx @k3a )
v1.6.1
PR #383 Fix missing labels for some replication metrics (thx @yz1509 )
=> redis_exporter - upstream releases

templating.yaml
CHANGES:
103: Switch to gcr.io/distroless/static image. Use a non-root user to run the exporter process by default. Thanks to Alex SZAKALY.
Update Go version to 1.14
BUGFIXES:
99: Fix link to metrics path. Thanks to Yoan Blanc.
101: docs: fix dockerfile link. Thanks to Eric Carboni.
=> Update Nginx exporter to 0.8.0

templating.yaml
* [CHANGE] Switch logging to go-kit #171
* [CHANGE] Fix metric types #182
* [CHANGE] Fix unit of time metric #183
* [FEATURE] Add filtering on server status #160
* [ENHANCEMENT] Add compression and server selection metrics #154
* [ENHANCEMENT] Add client/server abort metrics #167
* [ENHANCEMENT] Add version info metric (when using UNIX sockets) #180
Note: This release fixes the metric types of counters and renames the following metrics:
* `haproxy_exporter_csv_parse_failures` -> `haproxy_exporter_csv_parse_failures_total`
* `haproxy_exporter_total_scrapes` -> `haproxy_exporter_scrapes_total`
* `haproxy_server_check_duration_milliseconds` -> `haproxy_server_check_duration_seconds`
=> Update to haproxy_exporter 0.11.0

statsd_exporter/statsd_exporter.spec
---
0.17.0 / 2020-06-26
[CHANGE] Support non-timer distributions without unit conversion (#314)
[ENHANCEMENT] Offline configuration check (#312)
[ENHANCEMENT] Support the SignalFX tagging extension (#315)
[BUGFIX] Allow matching single-letter metric name components (#309)
Distribution and histogram events (type d, h) are now treated as distinct from timer events (type ms).
Their values are observed as they are, while timer events are converted from milliseconds to seconds.
To reflect this generalization, the observer_type mapping option replaces timer_type.
Similary, change match_metric_type: timer to match_metric_type: observer.
The old name remains available for compatibility.
For users of the mapper library, the ObserverEvent replaces TimerEvent.
For timer metrics, it is emitted by the …
=> Update statsd_exporter to 0.17.0

templating.yaml
This release modifies the way the exporter is configured to use a modules/probers structure as seen in the blackbox_exporter.
This should be a no-op for the majority of users, however please note the following:
The --tls.insecure, --tls.cacert, --tls.client-auth, --tls.cert and --tls.key options have been removed. Please define a module with the corresponding TLS options instead. Refer to the example.
If you were relying on http proxying or other http client features, you will need to update your scrape config to use the https prober module, rather than relying on the exporter comprehending the scheme of the target. This is covered in the README.
Some new features have been introduced as well:
Support for setting TLS servername
STARTTLS support for smtp, imap and ftp
Defining a http proxy …
=> Update SSL exporter to 2.0.0

Makefile, ssl_exporter/ssl_exporter.default, ssl_exporter/ssl_exporter.service, ssl_exporter/ssl_exporter.spec, ssl_exporter/ssl_exporter.yml, templating.yaml
ssl_exporter 2.x switched to using a blackbox-style config file, specifying various modules for skipping TLS verification, setting SNI, etc.
Include the sample config file from the repo in the package.
=> ssl_exporter: include sample config file

memcached_exporter/memcached_exporter.spec
[CHANGE] Switch logging to go-kit #73
[CHANGE] Register memcached_lru_crawler_starts_total metric correctly (formerly namespace_lru_crawler_starts) #83
[ENHANCEMENT] Add memcached_time_seconds metric #74
[ENHANCEMENT] Add slab metrics related to hot/warm/cold/temp LRUs #76
[BUGFIX] Fix memcached_slab_mem_requested_bytes metric in newer memcached versions #70
=> Update memcached exporter to 0.7.0

jmx_exporter/jmx_exporter.spec
[FEATURE] Added support for jmx attributes of type java.util.Date (#449)
[ENHANCEMENT] Include error message with exception when the agent fails to start. (#399)
[ENHANCEMENT] Allow specifying IPv6 address to bind to (#450)
[ENHANCEMENT] Bump client_java to 0.9.0, including adding /-/healthy (#495)
[BUGFIX] Handle NullPointerException for getAttributes (#444)
=> Update JMX exporter to 0.13.0

thanos/thanos.spec
Highlights:
Added new Thanos component: Query Frontend responsible for response caching,
query scheduling and parallelization (based on Cortex Query Frontend).
Added various new, improved UIs to Thanos based on React: Querier' BuildInfo & Flags, Ruler UI, BlockViewer.
Optimized Sidecar, Store, Receive, Ruler data retrieval with new TSDB ChunkIterator, capping chunks to 120 samples, fixed various leaks.
Fixed sample limit on Store Gateway.
Added S3 Server Side Encryption options.
Tons of other important fixes!
Thanks to all contributors! 🤗
Fixed
#2665 Swift: Fix issue with missing Content-Type HTTP headers.
#2800 Query: Fix handling of --web.external-prefix and --web.route-prefix.
#2834 Query: Fix rendered JSON state value for rules and alerts should be in lowercase.
#2866 Receive, …
=> Update Thanos to 0.15.0

prometheus2/prometheus2.spec
This release is built with Go 1.15, which deprecates X.509 CommonName
in TLS certificates validation.
In the unlikely case that you use the gRPC API v2 (which is limited to TSDB
admin commands), please note that we will remove this experimental API in the
next minor release 2.22.
[CHANGE] Disable HTTP/2 because of concerns with the Go HTTP/2 client. #7588 #7701
[CHANGE] PromQL: query_log_file path is now relative to the config file. #7701
[CHANGE] Promtool: Replace the tsdb command line tool by a promtool tsdb subcommand. #6088
[CHANGE] Rules: Label rule_group_iterations metric with group name. #7823
[FEATURE] Eureka SD: New service discovery. #3369
[FEATURE] Hetzner SD: New service discovery. #7822
[FEATURE] Kubernetes SD: Support Kubernetes EndpointSlices. #6838
[FEATURE] Scrape: Add …
=> Update Prometheus to 2.21.0

mtail/mtail.default, mtail/mtail.service, mtail/mtail.spec
Some quirks with mtail:
- I specify '-logs /var/log/messages' in the defaults file, so it will at least start, but people will really want to configure that specifically for their needs;  this exposes just a count of lines in /var/log/messages, which seems innocuous to me.
Should I leave it so the service won't even start without editing the defaults?
I define bin_version as '3.0.0-rc36' (which matches the binary) and the package version as '3.0.0rc36', since you can't have a dash in there - not sure there's a clever way to avoid having to have both defined.
=> add mtail package

ssl_exporter/ssl_exporter.spec
Bump to 2.1.0
---
c0f4183 release 2.1.0
17aa4e2 Add metrics for certificates in the verified chains (#48)
ddedd5f Add more information to error logs (#49)
ac9bc31 add a file name extension to the generated binary when the host (e.g. windows) requires it (#47)
b4b8471 build windows release (#43)
=> ssl_exporter upstream release - 2.1.0

templating.yaml
Add support to the frr_bgp_peer_prefixes_received_count_total metric for newer versions of FRR
=> Update FRR exporter to 0.2.9

ssl_exporter/ssl_exporter.spec
---
v2.1.1
@ribbybibby ribbybibby released this 7 days ago
Changelog
224fb62 release 2.1.1
b84db80 Fix ssl_verified_cert_not_after typo
=> Update ssl_exporter to 2.2.1

templating.yaml
Update Redis exporter to 1.12.0 and fix license.
=> Update Redis exporter to 1.12.0

blackbox_exporter/blackbox_exporter.spec
[ENHANCEMENT] Expose probe_dns_duration_seconds metric (#662)
[ENHANCEMENT] Add probe_icmp_reply_hop_limit (#694)
[ENHANCEMENT] prober/tls: adding metric to expose certificate fingerprint info (#678)
[BUGFIX] prober/tls: fix probe_ssl_last_chain_expiry_timestamp_seconds (#681)
[BUGFIX] Fix incorrect content length reporting when using regexes (#674)
[BUGFIX] Fix panic when running ICMPv4 probe with DontFragment (#686)
[BUGFIX] Deal with URLs with literal IPv6 addresses (#645)
[BUGFIX] Change DoT default port to 853 (#655)
=> Update Blackbox Exporter to 0.18.0

statsd_exporter/statsd_exporter.spec
[ENHANCEMENT] Allow turning off tagging extensions (#325)
[ENHANCEMENT] Add a lifecycle API for configuration reloads and restarts (#329)
This release changes the interface for the github.com/prometheus/statsd_exporter/pkg/line library package to support the new configurability.
=> Update statsd exporter to 0.18.0

prometheus2/prometheus2.spec
[CHANGE] web: Remove APIv2. #7935
[ENHANCEMENT] React UI: Implement missing TSDB head stats section. #7876
[ENHANCEMENT] UI: Add Collapse all button to targets page. #6957
[ENHANCEMENT] UI: Clarify alert state toggle via checkbox icon. #7936
[ENHANCEMENT] Add rule_group_last_evaluation_samples and prometheus_tsdb_data_replay_duration_seconds metrics. #7737 #7977
[ENHANCEMENT] Gracefully handle unknown WAL record types. #8004
[ENHANCEMENT] Issue a warning for 64 bit systems running 32 bit binaries. #8012
[BUGFIX] Adjust scrape timestamps to align them to the intended schedule, effectively reducing block size. Workaround for a regression in go1.14+. #7976
[BUGFIX] promtool: Ensure alert rules are marked as restored in unit tests. #7661
[BUGFIX] Eureka: Fix service discovery when compiled in …
=> Update Prometheus to 2.22.0

templating.yaml
BGP peers with a state of Idle (Admin) now return a value of 2 for the frr_bgp_peer_state metric.
=> Update FRR exporter to 0.2.10

openstack_exporter/openstack_exporter.spec
The following fixes and metrics have been included on this release:
Metrics with L3agents for routers (#129)
Remove loadbalancer metrics from neutron (#128)
Fix gnocchi tests [disabled for now]
Implemented gnocchi exporter with 4 new metrics (#125)
Admin state for ports (#126)
Metrics for each Floating IP (#124)
Add hypervisor_hostname label to Nova server_status metric (#123)
add uuid to agent_state fields (#116)
Add Ironic node state exporter (#113)
Update README.md (#111)
Fix dns metrics for all projects (#109)
=> Update OpenStack exporter to 1.2.0

thanos/thanos-compact.default, thanos/thanos-query.default, thanos/thanos-rule.default, thanos/thanos-store.default, thanos/thanos.spec
Highlights:
New Thanos component, Query Frontend has more options and supports shared cache (currently: Memcached).
Added debug mode in Thanos UI that allows to filter Stores to query from by their IPs from Store page (!). This helps enormously in e.g debugging the slowest store etc. All raw Thanos API allows passing
storeMatch[] arguments with __address__ matchers.
Improved debuggability on all Thanos components by exposing off-CPU profiles thanks to fgprof endpoint.
Significantly improved sidecar latency and CPU usage for metrics fetches.
Fixed
#3234 UI: Fix assets not loading when --web.prefix-header is used.
#3184 Compactor: Fixed support for web.external-prefix for Compactor UI.
Added
#3114 Query Frontend: Added support for Memacached cache.
breaking Renamed flag …
=> Update Thanos to 0.16.0

templating.yaml
PR #444 - fix count-keys command line option (thx @laubstein )
PR #442 - add sentinel metrics (thx @rayanimesh )
PR #436 - bumped Prometheus library from 1.7.1 to 1.8.0
=> Update Redis Exporter to 0.13.1

prometheus2/prometheus2.spec
[BUGFIX] Fix potential "mmap: invalid argument" errors in loading the head chunks, after an unclean shutdown, by performing read repairs. #8061
[BUGFIX] Fix serving metrics and API when reloading scrape config. #8104
[BUGFIX] Fix head chunk size calculation for size based retention. #8139
=> Update prometheus to 2.22.1

thanos/thanos.spec
Highlights
BlockViewer now allows downloading meta.json of a block directly from Compact/Web UI.
thanos query-frontend now supports query splitting and retries for label names and label values APIs.
thanos tools bucket replicate can now copy particular block s by ID or time range.
thanos query is now using dynamic lookback delta when downsampled data is used by default.
More katacoda tutorials!
Compactor is aware of 64GB index size limits and automatically avoids compacting blocks to a bigger size than this. Admin can
also manually exclude block from further compaction by uploading no-compact-mark.json file to bucket block directory.
Added thanos tools bucket mark for marking blocks with no compact or delayed deletion marker.
When enabled ( --store.enable-index-header-lazy-reader flag), …
=> Update Thanos to 0.17.0

thanos/thanos.spec
Fixed
#3480 Query-frontend: Fixed regression.
Changed
#3498 Enabled debug.SetPanicOnFault(true) which allow us to recover on queries causing SEG FAULTs (e.g unmmaped memory access).
=> Update Thanos to 0.17.1

templating.yaml
PMM-6811: Secondary lag reported as 136 years
=> Update mongodb exporter to 0.20.1

memcached_exporter/memcached_exporter.spec
[FEATURE] Support MySQL's InnoDB memcached plugin (by handling their multi-word stats settings values)
[FEATURE] Make exporter logic available as standalone library package #97
[ENHANCEMENT] Add --version flag and version metric #99
[ENHANCEMENT] Update prometheus client library
=> memcached_exporter upstream release: 0.8.0

ssl_exporter/ssl_exporter.spec
This release includes a number of new features:
OCSP stapling metrics
Prober for certificates in Kubernetes secrets
Prober for certificates in local files
Configurable timeout for modules
Please note that the ssl_tls_connect_success metric has been renamed to ssl_probe_success.
5d3ac12 release 2.2.0
44d8713 Add test for TLS version metric
8cde56c Fix examples in the README
fdda9c3 Add prober column to metrics table
d92d7be Add file prober to example config
ca7aa1f Fix golint errors
13a03b1 Move tests to prober package
67539b6 Use same results check for file + kube probes
f4782e3 Make the description in the README more succinct
63dcb9a Add kubernetes prober
0506638 Add file prober
c74c0de Refactor prober function and metrics collection
e05745b Export OCSP stapling metrics (#54)
896b59b …
=> ssl_exporter - upstream release 2.2.0

thanos/thanos.spec
---
#3532 compact: do not cleanup blocks on boot. Reverts the behavior change introduced in #3115 as in some very bad cases the boot of Thanos Compact took a very long time since there were a lot of blocks-to-be-cleaned.
#3520 Fix index out of bound bug when comparing ZLabelSets.
=> Upstream release - Thanos 0.17.2

templating.yaml
PR #462 - allow configuring whether the port is included in the client's details (by default it is not)
=> Update Redis exporter to 1.14.0

openstack_exporter/openstack_exporter.spec
8bf713c fixes #122 (#150)
8e56979 Bind a exporter to only needed tcp version (#147)
3f31226 Add limits values for instances (#149)
9a9210d Add volume_status_counter metric (#143)
12e1802 Add support for multiple clouds (#141)
4fc2447 add metric free_disk_bytes for hypervisors (#145)
486e009 Add support for proxy (#140)
1fede2f Resolve #135 (#138)
ce689fe Add option to disable slow metrics. (#134)
a8ccd28 Add project_info metrics (#131)
=> Update OpenStack exporter to 1.3.0

templating.yaml
PR #457 Support for memory usage aggregation by key groups (thanks @rmak-cpi )
PR #466 Bump prometheus/client_golang library from 1.8.0 to 1.9.0
=> Update Redis Exporter to 1.15.0

Makefile
Switch to GitHub docker image repository to avoid issues with Docker Hub rate limits.
=> Switch to GitHub docker image repository

statsd_exporter/statsd_exporter.spec
0.19.0 / 2021-01-22
[CHANGE] [library] Require explicit Registerer (#347)
[ENHANCEMENT] Add /-/healthy and /-/ready endpoints (#339)
[BUGFIX] Do not open network ports when only checking config (#357)
=> statsd_exporter upstream release, 0.19.0

mtail/mtail.spec
Upstream releases
v3.0.0-rc43
Changelog
cc69d15 Switch the store RWMutex to a pair of categorical mutices.
9e0c20e Benchmark adds to the metrics store.
77cb9d6 No need for IMPORTS definition with go mod download.
c277f15 Use go mod download to fetch deps instead of doing it manually.
8262f12 Remove crossbuild target now we use goreleaser.
73d14bf Don't include Merge commits in changelog.
b2de91a Remove unused parameter from TestStartServer.
c9a2351 Reenable the unix socket listen test.
v3.0.0-rc42
Changelog
7609963 Add a new TODO.
1aac176 Avoid faffing with text processing in shell for benchstat.
4462ae8 Count when logstream fds are closed and use that to fix test flake.
9894852 Do benchstat in text not HTML.
8a9021a Fix order of arguments in TestMakeServer.
25ca804 Fix typo in autoreview …
=> mtail upstream release - 3.0.0-rc43

templating.yaml
41a2381 fix: lint issues
824a51e feat: latest deps
f86c47f feat: .im tld date format (#82)
a896661 chore(deps): bump github.com/stretchr/testify from 1.6.1 to 1.7.0 (#81)
f6947b1 chore(deps): bump github.com/prometheus/client_golang (#80)
55d4f7e chore(deps): bump github.com/prometheus/client_golang from 1.7.1 to 1.8.0
86217ff chore: lint issues
73cbe54 chore(deps): bump github.com/prometheus/common from 0.13.0 to 0.15.0 (#79)
=> Update Domain Exporter to 1.9.0

templating.yaml
Release notes: https://github.com/oliver006/redis_exporter/releases/tag/v1.16.0
=> Update Redis Exporter to 1.16.0

statsd_exporter/statsd_exporter.spec
Upstream releases 0.19.1 and 0.20.0:
---
This is a double-release because I had forgotten to hit "publish" on 0.19.1.
A big thank you goes to @glightfoot for providing both changes.
/MR
0.19.1 / 2021-01-29
[BUGFIX] Don't return empty responses to lifecycle api requests (#360)
0.20.0 / 2021-02-05
[ENHANCEMENT] Support full defaults for summaries and histograms (#361)
This completes support for summary_options and histogram_options.
Change the legacy configuration attributes throughout the mapping configuration as follows:
quantiles: … to summary_options: { quantiles: … }
buckets: … to histogram_options: { buckets: … }
timer_type to observer_type.
Support for the deprecated attributes will be removed in a future release.
=> statsd_exporter upstream release, 0.20.0

templating.yaml
Release notes: https://github.com/prometheus/node_exporter/releases/tag/v1.1.0
=> Update Node Exporter to 1.1.0

templating.yaml
Release notes: https://github.com/tynany/frr_exporter/releases/tag/v0.2.11
=> Update FRR exporter to 0.2.11

jmx_exporter/jmx_exporter.spec
Release notes: https://github.com/prometheus/jmx_exporter/releases/tag/parent-0.15.0
=> Update JMX exporter to 0.15.0

mtail/mtail.spec
v3.0.0-rc44
Changelog
499147e Downgrade the timed out message from pipestream as it's expected.
641107c Bump go.opencensus.io from 0.22.5 to 0.22.6
ad985d8 SIGHUP reload: fix empty path check
7339959 Robustify TestServer.GetProgramMetric.
dc34c39 Simplify test data by creating a MetricSlice.
22f0dc6 Use the Range method in benchmark to ensure iteration over all metrics.
7138405 Set benchmark timeout to 120m.
c64d3e1 Make the Store's mutexes internal.
7efe686 Move the FindMetricOrNil method from reader to Store.
c3f06fb Convert prometheus export to use store.Range.
a71fa5f Emit Metric.Source in the JSON output.
0c74e45 Add a Range method to Store.
ab3cbf2 Move the metrics store dump to the main function.
94f1600 Update some comments in examples.
dacf36e Remove a completed …
=> mtail upstream release - 3.0.0rc44

snmp_exporter/snmp_exporter.spec
Release notes: https://github.com/prometheus/snmp_exporter/releases/tag/v0.20.0
=> Update SNMP exporter to 0.20.0

templating.yaml
Release notes: https://github.com/oliver006/redis_exporter/releases/tag/v1.17.0
=> Update Redis Exporter to 1.17.0

postgres_exporter/postgres_exporter.spec, postgres_exporter/postgres_exporter_queries.yaml
First release under the Prometheus Community organisation.
[CHANGE] Update build to use standard Prometheus promu/Dockerfile
[ENHANCEMENT] Remove duplicate column in queries.yml #433
[ENHANCEMENT] Add query for 'pg_replication_slots' #465
[ENHANCEMENT] Allow a custom prefix for metric namespace #387
[ENHANCEMENT] Improve PostgreSQL replication lag detection #395
[ENHANCEMENT] Support connstring syntax when discovering databases #473
[ENHANCEMENT] Detect SIReadLock locks in the pg_locks metric #421
[BUGFIX] Fix pg_database_size_bytes metric in queries.yaml #357
[BUGFIX] Don't ignore errors in parseUserQueries #362
[BUGFIX] Fix queries.yaml for AWS RDS #370
[BUGFIX] Recover when connection cannot be established at startup #415
[BUGFIX] Don't retry if an error occurs #426
[BUGFIX] Do not …
=> postgres_exporter upstream release 0.9.0

.github/workflows/check_new_versions.yml, update_templating_versions.py
Add script and GitHub action to automatically update package versions to latest releases in `templating.yaml` file.
Sample output of the script:
```
$ python3 update_templating_versions.py 
INFO:root:Checking updates for NODE EXPORTER
INFO:root:Latest node_exporter release version: 1.1.1
INFO:root:node_exporter: current version: 1.1.0, latest version 1.1.1
INFO:root:Branch 'node_exporter_1_1_1' is already present, not pushing updates
INFO:root:Checking updates for MYSQLD EXPORTER
INFO:root:Latest mysqld_exporter release version: 0.12.1
INFO:root:mysqld_exporter: current version: 0.12.1, latest version 0.12.1
INFO:root:Checking updates for REDIS EXPORTER
INFO:root:Latest redis_exporter release version: 1.17.0
INFO:root:redis_exporter: current version: 1.16.0, latest version 1.17.0 …
```
=> Add script and GitHub action to automatically update templated packages.

templating.yaml
https://github.com/prometheus/node_exporter/releases/tag/v1.1.2
Release notes:
```
* [BUGFIX] Handle errors from disabled PSI subsystem #1983
* [BUGFIX] Sanitize strings from /sys/class/power_supply #1984
* [BUGFIX] Silence missing netclass errors #1986
```
=> Update node_exporter from 1.1.1 to 1.1.2

update_templating_versions.py
Check if GH release is not draft or prerelease, use tag instead of title for version extract.
=> Fix new exporter version checks

prometheus2/prometheus2.spec
[BUGFIX] Fix a crash in promtool when a subquery with default resolution is used. #8569
[BUGFIX] Fix a bug that could return duplicate datapoints in queries. #8591
[BUGFIX] Fix crashes with arm64 when compiled with go1.16. #8593
=> Update Prometheus to 2.25.1

prometheus2/prometheus2.spec
```
[BUGFIX] Fix the ingestion of scrapes when the wall clock changes, e.g. on suspend. #8601
```
=> Update Prometheus to 2.25.2

templates/spec.tpl, templating.yaml
Add auto generated package additional source support (additional configuration files etc.)
This will allow to migrate multiple manually maintained packages to auto generated ones.
=> Additional sources support

thanos/thanos.spec
Release notes:
```
Added
#3700 Compact/Web: Make old bucket viewer UI work with vanilla Prometheus blocks.
#3657 *: It's now possible to configure HTTP transport options for S3 client.
#3752 Compact/Store: Added --block-meta-fetch-concurrency allowing to configure number of go routines for block metadata synchronization.
#3723 Query Frontend: Added --query-range.request-downsampled flag enabling additional queries for downsampled data in case of empty or incomplete response to range request.
#3579 Cache: Added inmemory cache for caching bucket.
#3792 Receiver: Added --tsdb.allow-overlapping-blocks flag to allow overlapping tsdb blocks and enable vertical compaction.
#3740 Query: Added --query.default-step flag to set default step. Useful when your tenant scrape interval is stable and far …
```
=> Update Thanos to 0.19.0

Makefile
RHEL 8  has replaced docker with podman, and podman does not create directories when mounting them.
This pull-request fixes that.
=> Modify Makefile in order to be compatible with Podman

templating.yaml
I was bitten by 'too many open files' with blackbox_exporter (I was having a timeout issue and connections pile-up when that happens).
Is 16k enough?
=> Set open_file_limit  for blackbox_exporter

prometheus2/prometheus2.spec
Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.28.0
=> Update Prometheus to 2.28.0

templating.yaml
For large SNMP installations (like mine), 1,024 is a bit low.
Signed-off-by: Ben Ritcey <ben+github@ritcey.com>
=> snmp_exporter: set open_file_limit to 16k

prometheus2/prometheus2.spec, templates/unit.tpl, templating.yaml
The templated systemd unit file doesn't have a Reload action - 'kill -HUP $MAINPID' looks to have been fairly standard.
Is this fine to have by default or should it be something explicitly enabled via a switch in templating.yml?
=> add ExecReload to unit

jmx_exporter/jmx_exporter.spec
Release notes: https://github.com/prometheus/jmx_exporter/releases/tag/parent-0.16.0
=> Update JMX exporter to 0.16.0

Makefile, templating.yaml
This adds [artifactory_exporter](https://github.com/peimanja/artifactory_exporter). This was tested on an EL7-compatible system running 6.23.23.
`ARTI_USERNAME` and `ARTI_PASSWORD` needs to be set manually in `/etc/default/artifactory_exporter`. I wasn't sure if it was appropriate to define them via `environment` but leave them blank or not.
=> Add artifactory_exporter

thanos/thanos-receive.default, thanos/thanos-receive.service, thanos/thanos.spec
Add unit file & defaults for Thanos' "receive" remote-write component.
It won't quite start with provided defaults (--label is mandatory, etc.) - should we stub it out so it starts?
I set the data dir to /var/lib/thanos/receive;  this is similar, data-wise, to the /var/lib/prometheus/data we use elsewhere, but I didn't want to use /var/lib/prometheus/data and risk someone accidentally starting up thanos-receive on an active Prometheus instance, as it would want to change any existing TSDB it found ("found legacy storage, migrating to multi-tsdb layout with default tenant").
=> add thanos-receive to thanos package

Makefile, templating.yaml
Works out of the box with the default pgbouncer configuration. Tested with 1.15.0 on EL7-compatible system.
=> Add pgbouncer_exporter

prometheus2/prometheus2.spec
Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.29.0
=> Update Prometheus to 2.29.0

prometheus2/prometheus2.spec
Release notes:
https://github.com/prometheus/prometheus/releases/tag/v2.30.2
=> Update Prometheus to 2.30.2

templates/spec.tpl
Add support for source binaries that are not packaged as TAR archives, useful for exporter like `ebpf exporter` where only binary files are released.
=> Add support for binaries

thanos/thanos-query.default, thanos/thanos.spec
Update Thanos Query defaults as store parameter has been deprecated and replaced by endpoint parameter
=> Update Thanos Query defaults

jmx_exporter/jmx_exporter.spec
Release notes: https://github.com/prometheus/jmx_exporter/releases/tag/parent-0.17.0
=> Update JMX exporter to 0.17.0

Makefile, templating.yaml
Add dellhw_exporter from https://github.com/galexrt/dellhw_exporter for Dell/EMC machines with running OMSA.
=> Add dellhw_exporter

prometheus2/prometheus2.spec
Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.38.0
=> Update Prometheus to 2.38.0

.github/workflows/build.yml, Makefile, README.md
Requires https://github.com/lest/centos-rpm-builder-docker/pull/5
=> add a build target for CentOS Stream 9

jmx_exporter/jmx_exporter.spec
Updates jmx_exporter to the latest release as seen here: https://github.com/prometheus/jmx_exporter/releases
=> update jmx_exporter to 0.17.2

Makefile, templating.yaml
This MR adds Exim4 exporter from https://github.com/gvengel/exim_exporter. To be able to access Exim logs it has to be run from `exim` user.
=> Add Exim4 exporter from https://github.com/gvengel/exim_exporter

Makefile, templating.yaml
Prometheus community wrote systemd exporter. It would be useful to use it and have rpm packagest
=> feat: build systemd exporter

templating.yaml, update_templating_versions.py
Set large `yaml.width` value in `update_templating_versions.py` to avoid outputting YAML with trailing whitespace, such as
```yaml
path:
https://example.com/
```
Also add starting whitespace in `templating.yaml` comments, and unwrap long lines to match the output of
`update_templating_versions.py`.
=> Fix YAML lint issues

templating.yaml
[ENHANCEMENT] Add 1kB and 2kB units https://github.com/prometheus-community/postgres_exporter/pull/915
[BUGFIX] Add error log when probe collector creation fails https://github.com/prometheus-community/postgres_exporter/pull/918
[BUGFIX] Fix test build failures on 32-bit arch https://github.com/prometheus-community/postgres_exporter/pull/919
[BUGFIX] Adjust collector to use separate connection per scrape https://github.com/prometheus-community/postgres_exporter/pull/936
That last one created a lot of issues for some deployments.
=> postgres_exporter got updated to 0.15.0, closing critical issue with exhausting of the server pool connections.

prometheus2/prometheus2.spec
Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.48.0
=> Update Prometheus to 2.48.0

.github/workflows/build.yml
Currently all builds fail on el7 packaging as the upstream el7 mirrors have been removed following the EOL of el7.
=> ci: remove el7 as it is EOL and causes builds to fail
