Makefile
graphite_exporter/graphite_exporter.service
graphite_exporter/graphite_exporter.spec

Added graphite exporter to rpm

add graphite exporter 0.2.0

---

blackbox_exporter/blackbox_exporter.default
blackbox_exporter/blackbox_exporter.service

As previously agreed, moved configuration file declaration place from systemd .service file to defaults file.

Changing config file declaration place.

---

Makefile
consul_exporter/consul_exporter.service
consul_exporter/consul_exporter.spec

add consul exporter

---

Makefile
apache_exporter/apache_exporter.service
apache_exporter/apache_exporter.spec

Add apache_exporter

---

Makefile
redis_exporter/redis_exporter.service
redis_exporter/redis_exporter.spec

Added the [Redis exporter](https://github.com/oliver006/redis_exporter/) from @oliver006

Added Redis exporter

---

Makefile
sachet/sachet.default
sachet/sachet.service
sachet/sachet.spec
sachet/sachet.yml

SMS alerts for Prometheus' Alertmanager

Add package sachet

---

prometheus2/prometheus.service
prometheus2/prometheus2.spec

Prometheus 2.1.0

---

Makefile
postgres_exporter/postgres_exporter.service
postgres_exporter/postgres_exporter.spec

Add postgres_exporter from https://github.com/wrouesnel/postgres_exporter

Add postgres_exporter

---

Makefile
collectd_exporter/collectd_exporter.service
collectd_exporter/collectd_exporter.spec

Add RPM build for collectd_exporter: https://github.com/prometheus/collectd_exporter

Collectd exporter

---

prometheus2/prometheus2.spec

- [BUGFIX] Fix data loss in TSDB on compaction
- [BUGFIX] Correctly stop timer in remote-write path
- [BUGFIX] Fix deadlock triggered by loading targets page
- [BUGFIX] Fix incorrect buffering of samples on range selection queries
- [BUGFIX] Handle large index files on windows properly

Adding Prometheus 2.2.1 support

---

snmp_exporter/snmp_exporter.spec

Bump snmp_exporter to 0.9

---

Makefile
statsd_exporter/statsd_exporter.service
statsd_exporter/statsd_exporter.spec

Adding the official statsd_exporter. https://github.com/prometheus/statsd_exporter

Add statsd_exporter to the list of packages to build

---

templating.yaml

#54  Upgrading MySQLd exporter

Upgrade MySQLd Exporter

---

consul_exporter/consul_exporter.spec

Newer version of consul exporter

Bump consul exporter version

---

statsd_exporter/statsd_exporter.spec

Increase version of statsd exporter

Bump version of statsd exporter

---

prometheus2/prometheus2.spec

Pretty simple version bump for new release of prometheus

Prometheus version bump

---

prometheus2/prometheus2.spec

Prometheus version bump 2.7.0

---

alertmanager/alertmanager.spec

https://github.com/prometheus/alertmanager/releases/tag/v0.16.1

Update Alertmanager to 0.16.1

---

prometheus2/prometheus2.spec

Prometheus version bump - 2.8.0

---

thanos/thanos-query.default
thanos/thanos-rule.default
thanos/thanos-rule.service
thanos/thanos.spec
thanos/thanos_alerts.yml

Add service and defaults for thanos rule, create required directories.

Thanos improvements

---

thanos/thanos-query.default
thanos/thanos-rule.default
thanos/thanos-rule.service
thanos/thanos-sidecar.default
thanos/thanos-store.default
thanos/thanos.spec

Update Thanos to 0.4.0 and fix thanos rule service.

Update Thanos to 0.4.0

---

prometheus2/prometheus2.spec

Updated prometheus to version 2.10.0

Update prometheus version

---

Makefile
process_exporter/process_exporter.default
process_exporter/process_exporter.service
process_exporter/process_exporter.spec
process_exporter/process_exporter.yml

Add Process Exporter 0.5.0.
Note: I've renamed binary from `process-exporter` to `process_exporter`, please review if that is OK.

Add process_exporter package

---

templating.yaml

https://github.com/nginxinc/nginx-prometheus-exporter/releases/tag/v0.4.1

NGINX Prometheus Exporter 0.4.1

---

thanos/thanos.spec

Changed:
#1409 SECURITY Fixed a XSS vulnerability in Querier UI query history.

Update to Thanos 0.6.1

---

prometheus2/prometheus2.spec

[BUGFIX/SECURITY] Fix a Stored DOM XSS vulnerability with query history. #5888

Update to Prometheus 2.11.2

---

prometheus2/prometheus2.spec

Changes:
[FEATURE] Track currently active PromQL queries in a log file. #5794
[FEATURE] Enable and provide binaries for mips64 / mips64le architectures. #5792
[ENHANCEMENT] Improve responsiveness of targets web UI and API endpoint. #5740
[ENHANCEMENT] Improve remote write desired shards calculation. #5763
[ENHANCEMENT] Flush TSDB pages more precisely. tsdb#660
[ENHANCEMENT] Add prometheus_tsdb_retention_limit_bytes metric. tsdb#667
[ENHANCEMENT] Add logging during TSDB WAL replay on startup. tsdb#662
[ENHANCEMENT] Improve TSDB memory usage. tsdb#653, tsdb#643, tsdb#654, tsdb#642, tsdb#627
[BUGFIX] Check for duplicate label names in remote read. #5829
[BUGFIX] Mark deleted rules' series as stale on next evaluation. #5759
[BUGFIX] Fix JavaScript error when showing warning about out-of-sync …

Update to Prometheus 2.12.0

---

prometheus2/prometheus2.spec

[SECURITY/BUGFIX] UI: Fix a Stored DOM XSS vulnerability with query history CVE-2019-10215. #6098
[CHANGE] Metrics: renamed prometheus_sd_configs_failed_total to prometheus_sd_failed_configs and changed to Gauge #5254
[ENHANCEMENT] Include the tsdb tool in builds. #6089
[ENHANCEMENT] Service discovery: add new node address types for kubernetes. #5902
[ENHANCEMENT] UI: show warnings if query have returned some warnings. #5964
[ENHANCEMENT] Remote write: reduce memory usage of the series cache. #5849
[ENHANCEMENT] Remote read: use remote read streaming to reduce memory usage. #5703
[ENHANCEMENT] Metrics: added metrics for remote write max/min/desired shards to queue manager. #5787
[ENHANCEMENT] Promtool: show the warnings during label query. #5924
[ENHANCEMENT] Promtool: improve error …

Update to Prometheus 2.13.0

---

prometheus2/prometheus2.spec

[BUGFIX] Fix panic in ARM builds of Prometheus. #6110
[BUGFIX] promql: fix potential panic in the query logger. #6094
[BUGFIX] Multiple errors of http: superfluous response.WriteHeader call in the logs. #6145

Update to Prometheus 2.13.1

---

apache_exporter/apache_exporter.spec
elasticsearch_exporter/elasticsearch_exporter.spec

* Upgrade apache_exporter to v0.7.0
* Upgrade elasticsearch_exporter to 1.1.0

Upgrade exporters

---

prometheus2/prometheus2.spec

---
* [SECURITY/BUGFIX] UI: Ensure warnings from the API are escaped. #6279
* [FEATURE] API: /api/v1/status/runtimeinfo and /api/v1/status/buildinfo endpoints added for use by the React UI. #6243
* [FEATURE] React UI: implement the new experimental React based UI. #5694 and many more
Can be found by under /new.
Not all pages are implemented yet.
* [FEATURE] Status: Cardinality statistics added to the Runtime & Build Information page. #6125
* [ENHANCEMENT/BUGFIX] Remote write: fix delays in remote write after a compaction. #6021
* [ENHANCEMENT] UI: Alerts can be filtered by state. #5758
* [BUGFIX] API: lifecycle endpoints return 403 when not enabled. #6057
* [BUGFIX] Build: Fix Solaris build. #6149
* [BUGFIX] Promtool: Remove false duplicate rule warnings when checking …

prometheus upstream release - 2.14.0

---

prometheus2/prometheus2.spec

'tsdb' was added in 2.13.0
Thanks to @xocasdashdash for catching that

include tsdb tool in package

---

pushgateway/pushgateway.spec

Upgrade pushgateway to 1.0.0

---

alertmanager/alertmanager.spec

[CHANGE] Check that at least one silence matcher matches a non-empty string. #2081
[ENHANCEMENT] [pagerduty] Check that PagerDuty keys aren't empty. #2085
[ENHANCEMENT] [template] Add the stringSlice function. #2101
[ENHANCEMENT] Add alertmanager_dispatcher_aggregation_groups and alertmanager_dispatcher_alert_processing_duration_seconds metrics. #2113
[ENHANCEMENT] Log unused receivers. #2114
[ENHANCEMENT] Add alertmanager_receivers metric. #2114
[ENHANCEMENT] Add alertmanager_integrations metric. #2117
[ENHANCEMENT] [email] Add Message-Id Header to outgoing emails. #2057
[BUGFIX] Don't garbage-collect alerts from the store. #2040
[BUGFIX] [ui] Disable the grammarly plugin on all textareas. #2061
[BUGFIX] [config] Forbid nil regexp matchers. #2083
[BUGFIX] [ui] Fix Silences UI when …

Update Alertmanager to 0.20.0

---

prometheus2/prometheus2.spec

Updated to latest prometheus version

---

Makefile
exporter_exporter/exporter_exporter.default
exporter_exporter/exporter_exporter.service
exporter_exporter/exporter_exporter.spec
exporter_exporter/exporter_exporter.yml

Initial add of exporter_exporter - includes commented-out examples in the config

add exporter_exporter

---

exporter_exporter/exporter_exporter.default
exporter_exporter/exporter_exporter.spec

Corrected exporter_exporter.defaults (and also ran through dos2unix)

corrected exporter_exporter defaults

---

prometheus2/prometheus2.spec

[FEATURE] React UI: Support local timezone on /graph #6692
[FEATURE] PromQL: add absent_over_time query function #6490
[FEATURE] Adding optional logging of queries to their own file #6520
[ENHANCEMENT] React UI: Add support for rules page and "Xs ago" duration displays #6503
[ENHANCEMENT] React UI: alerts page, replace filtering togglers tabs with checkboxes #6543
[ENHANCEMENT] TSDB: Export metric for WAL write errors #6647
[ENHANCEMENT] TSDB: Improve query performance for queries that only touch the most recent 2h of data. #6651
[ENHANCEMENT] PromQL: Refactoring in parser errors to improve error messages #6634
[ENHANCEMENT] PromQL: Support trailing commas in grouping opts #6480
[ENHANCEMENT] Scrape: Reduce memory usage on reloads by reusing scrape cache #6670
[ENHANCEMENT] Scrape: Add …

Update Prometheus to 2.16.0

---

Makefile
postgres_exporter/postgres_exporter.default
postgres_exporter/postgres_exporter.spec
postgres_exporter/postgres_exporter_queries.yaml
templating.yaml

Add queries.yaml configuration from unstream and remove postgres exporter from templated exporter configuration.

Postgres Exporter fixes

---

templates/init.tpl

adds return codes to status

---

iperf3_exporter/iperf3_exporter.spec

---
* add support to specify the target port for iperf testing

iperf3_exporter upstream release

---

prometheus2/prometheus2.spec

[BUGFIX] TSDB: Fix query performance regression that increased memory and CPU usage #7051

Update to Prometheus 2.17.1

---

templates/init.tpl
templates/spec.tpl
templates/unit.tpl

Attempt to fix https://github.com/lest/prometheus-rpm/issues/214

Fix templating with non-prometheus user

---

templating.yaml

Update NGINX exporter to 0.7.0

Update NGINX exporter to 0.7.0

---

Makefile
templating.yaml

Adding jolokia exporter for jolokia metric exposing to prometheus.

add jolokia_exporter

---

prometheus2/prometheus2.spec

[BUGFIX] TSDB: Fixed snapshot API. #7217

Update Prometheus to 2.18.1

---

prometheus2/prometheus2.spec

[BUGFIX] TSDB: Fix incorrect query results when using Prometheus with remote reads configured #7361

Update Prometheus to 2.18.2

---

prometheus2/prometheus2.spec

[FEATURE] TSDB: Memory-map full chunks of Head (in-memory) block from disk. This reduces memory footprint and makes restarts faster. #6679
[ENHANCEMENT] Discovery: Added discovery support for Triton global zones. #7250
[ENHANCEMENT] Increased alert resend delay to be more tolerant towards failures. #7228
[ENHANCEMENT] Remote Read: Added prometheus_remote_storage_remote_read_queries_total counter to count total number of remote read queries. #7328
[ENHANCEMEMT] Added time range parameters for label names and label values API. #7288
[ENHANCEMENT] TSDB: Reduced contention in isolation for high load. #7332
[BUGFIX] PromQL: Eliminated collision while checking for duplicate labels. #7058
[BUGFIX] React UI: Don't null out data when clicking on the current tab. #7243
[BUGFIX] PromQL: Correctly …

Update Prometheus to 2.19.0

---

templating.yaml

Updating ssl_exporter to 1.0.1

---

prometheus2/prometheus2.spec

[BUGFIX] TSDB: Fix m-map file truncation leading to unsequential files. #7414

Update prometheus to 2.19.1

---

blackbox_exporter/blackbox_exporter.spec

[FEATURE] Add none/all matches to DNS RRset validation (#552)
[FEATURE] Allow specifying DNS query Class (#635)
[FEATURE] Add support for DoT to DNS probes (#643) (#644)
[ENHANCEMENT] Add new probe_ssl_last_chain_expiry_timestamp_seconds metric (#636)
[ENHANCEMENT] Add probe_ip_addr_hash to detect if the IP changes (#584)
[ENHANCEMENT] Add support for "rootless" ping (#642)
[BUGFIX] Seed RNG to ensure different ICMP ids. (#638)

Update Blackbox Exporter to 0.17.0

---

thanos/thanos.spec

Highlights:
Rare overlapping block issue fixed
Deduplication bug with counters fixed
Receiver is now multi-tenant (multi TSDB)
Added @memcached meta and chunk caching. (e.g allows to significantly limit objstore traffic)
TSDB isolation added for Ruler and Receive
Querier performance significantly improved especially when used with duplicated Store APIs (e.g for HA purposes).
Thanks all for contributing! 🤗
Fixed
#2548 Query: Fixed rare cases of double counter reset accounting when querying rate with deduplication enabled.
#2536 S3: Fixed AWS STS endpoint url to https for Web Identity providers on AWS EKS.
#2501 Query: Gracefully handle additional fields in SeriesResponse protobuf message that may be added in the future.
#2568 Query: Don't close the connection of strict, static nodes if …

Update to Thanos 0.13.0

---

prometheus2/prometheus2.spec

[BUGFIX] Remote Write: Fix panic when reloading config with modified queue parameters. #7452

Update Prometheus to 2.19.2

---

prometheus2/prometheus2.spec

---
This release changes WAL compression from opt-in to default. WAL compression will prevent a downgrade to v2.10 or earlier without deleting the WAL. Disable WAL compression explicitly by setting the command line flag --no-storage.tsdb.wal-compression if you require downgrading to v2.10 or earlier.
[CHANGE] promtool: Changed rule numbering from 0-based to 1-based when reporting rule errors. #7495
[CHANGE] Remote read: Added prometheus_remote_storage_read_queries_total counter and prometheus_remote_storage_read_request_duration_seconds histogram, removed prometheus_remote_storage_remote_read_queries_total counter.
[CHANGE] Remote write: Added buckets for longer durations to prometheus_remote_storage_sent_batch_duration_seconds histogram.
[CHANGE] TSDB: WAL compression …

Update prometheus to 2.20.0

---

templating.yaml

PR #399 - Add TLS support to exporter (thx @schaefec )

Update redis exporter to 1.9.0

---

prometheus2/prometheus2.spec

[BUGFIX] SD: Reduce the Consul watch timeout to 2m and adjust the request timeout accordingly. #7724

Update to prometheus 2.20.1

---

process_exporter/process_exporter.spec

9760f38 Count usage of process start-up (#139)
d14dfc6 Add proportional resident memory size (#142)

Update Process exporter to 0.7.2

---

consul_exporter/consul_exporter.spec

[BUGFIX] Fix /metrics hanging when --consul.request-limit is lower than the number of services in Consul. #179

Update Consul exporter to 0.7.1

---

snmp_exporter/snmp_exporter.spec

[ENHANCEMENT] Support EnumAsInfo as an index (#559)
[ENHANCEMENT] Allow lookup chaining for uints (#527)

Update SNMP exporter to 0.19.0

---

templating.yaml

3b13ebe Update gopsutil
f9851ed Update ipvs

Update keepalived exporter to 0.5.0

---

thanos/thanos-compact.service
thanos/thanos-query-frontend.default
thanos/thanos-query-frontend.service
thanos/thanos-query.service
thanos/thanos-rule.service
thanos/thanos-store.service
thanos/thanos.spec

Add thanos-query-frontend service and update project and documentation URLs.

Add thanos-query-frontend service

---

Makefile

Actually adding mtail to Makefile this time

mtail: add mtail to Makefile

---

Makefile
openstack_exporter/openstack_exporter.default
openstack_exporter/openstack_exporter.service
openstack_exporter/openstack_exporter.spec
openstack_exporter/openstack_exporter_clouds.yaml

Resolves https://github.com/lest/prometheus-rpm/issues/110

Add OpenStack exporterr 1.1.0.

---

templating.yaml

[FEATURE] Add Docker image build for ppc64le architecture. #339
[ENHANCEMENT] Web UI: Add scroll bare to list of pushed metrics. #354
[ENHANCEMENT] Logging: Show remote address when failing to parse pushed metrics. #361
[BUGFIX] Web UI: Update JQuery to v3.5.1 to address security concerns. #360

Update pushgateway to 1.3.0

---

collectd_exporter/collectd_exporter.spec

[CHANGE] Switch logging to go-kit (#85)

Update collectd exporter to 0.5.0

---

mtail/mtail.spec

mtail - upstream release

---

templating.yaml

PR #428 - Add count-keys functionality (thx @felixb )

Update Redis Exporter to 1.12.1

---

generate.py

Fixes https://github.com/lest/prometheus-rpm/issues/288

Safely load YAML configuration

---

thanos/thanos-query-frontend.default
thanos/thanos-query-frontend.service
thanos/thanos.spec

Related to https://github.com/lest/prometheus-rpm/pull/287#issuecomment-718498393

Fix Thanos Query Frontend downstram url.

---

process_exporter/process_exporter.spec

Update dependencies and Go version to latest.

Update Process Exporter to 0.7.3

---

prometheus2/prometheus2.spec

[BUGFIX] Fix race condition in syncing/stopping/reloading scrapers. #8176

Update Prometheus to 2.22.2

---

process_exporter/process_exporter.spec

90d7869 Add exporter version metric
704cb9e Fix OPTS arguments

Update Process Exporter to 0.7.5

---

prometheus2/prometheus2.spec

[CHANGE] UI: Make the React UI default. #8142
[CHANGE] Remote write: The following metrics were removed/renamed in remote write. #6815
prometheus_remote_storage_succeeded_samples_total was removed and prometheus_remote_storage_samples_total was introduced for all the samples attempted to send.
prometheus_remote_storage_sent_bytes_total was removed and replaced with prometheus_remote_storage_samples_bytes_total and prometheus_remote_storage_metadata_bytes_total.
prometheus_remote_storage_failed_samples_total -> prometheus_remote_storage_samples_failed_total .
prometheus_remote_storage_retried_samples_total -> prometheus_remote_storage_samples_retried_total.
prometheus_remote_storage_dropped_samples_total -> prometheus_remote_storage_samples_dropped_total. …

Update Prometheus to 2.23.0

---

.travis.yml
Makefile

Fixes https://github.com/lest/prometheus-rpm/issues/302

Remove CentOS 6 builds

---

templating.yaml

[ENHANCEMENT] Add --version flag #189
[BUGFIX] Use newest Go version to fix random panic in the runtime
[BUGFIX] Fix typos in log messages #188 #191

Update HAproxy exporter to 0.12.0

---

prometheus2/prometheus2.spec

[FEATURE] Add TLS and basic authentication to HTTP endpoints. #8316
[FEATURE] promtool: Add check web-config subcommand to check web config files. #8319
[FEATURE] promtool: Add tsdb create-blocks-from openmetrics subcommand to backfill metrics data from an OpenMetrics file. #8084
[ENHANCEMENT] HTTP API: Fast-fail queries with only empty matchers. #8288
[ENHANCEMENT] HTTP API: Support matchers for labels API. #8301
[ENHANCEMENT] promtool: Improve checking of URLs passed on the command line. #7956
[ENHANCEMENT] SD: Expose IPv6 as a label in EC2 SD. #7086
[ENHANCEMENT] SD: Reuse EC2 client, reducing frequency of requesting credentials. #8311
[ENHANCEMENT] TSDB: Add logging when compaction takes more than the block time range. #8151
[ENHANCEMENT] TSDB: Avoid unnecessary GC runs after …

Update Prometheus to 2.24.0

---

templating.yaml

[ENHANCEMENT] Web UI: Improved metrics text alignment. #369
[BUGFIX] Web UI: Fix deletion of groups with empty label values. #377

Update Pushgateway to 1.3.1

---

templating.yaml

[CHANGE] Replace legacy common/log with promlog #85
[FEATURE] Add current recursive clients metric #74
[FEATURE] Add zone serial numbers as metrics #91
[FEATURE] Add TLS and basic authentication #94
[BUGFIX] Use uint64 for counters in v3 xml #70
[BUGFIX] Fix Gauge type for large gauges #90

Update Bind Exporter to 0.4.0

---

prometheus2/prometheus2.spec

[ENHANCEMENT] Cache basic authentication results to significantly improve performance of HTTP endpoints (via an update of prometheus/exporter-toolkit).
[BUGFIX] Prevent user enumeration by timing requests sent to authenticated HTTP endpoints (via an update of prometheus/exporter-toolkit).

Update Prometheus to 2.24.1

---

templating.yaml

PR #465 Add scrape password file support (thx @Ansen

Update Redis Exporter to 1.15.1

---

templating.yaml

Upstream release 1.4.0:
[FEATURE] Experimental! Add TLS and basic authentication to HTTP endpoints. #381

pushgateway upstream release - 1.4.0

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.18.0

Update Thanos to 0.18.0

---

exporter_exporter/exporter_exporter.spec

exporter_exporter upstream release - 0.4.2

---

smokeping_prober/smokeping_prober.spec

https://github.com/SuperQ/smokeping_prober/releases/tag/v0.4.1

Update Smokeping Prober to 0.4.1

---

junos_exporter/junos_exporter.spec
junos_exporter/junos_exporter.yaml

Release notes: https://github.com/czerwonk/junos_exporter/releases/tag/0.9.8

Update Junos Exporter to 0.9.8

---

templating.yaml

Do not use `%{name}` in URL as it doesn't expand in service files, other minor fixes.

Fix variable usage in template

---

.github/workflows/check_new_versions.yml
update_templating_versions.py

Adds labels depending on update severity. Will allow to further automate PR merging in future.

Add labels to generated PRs

---

templates/spec.tpl
templating.yaml

Add support for additional commands in %prep, %build, %install, %pre, %post, %preun and %postun sections.

Add support for additional commands

---

templates/spec.tpl
templating.yaml

Should resolve https://github.com/lest/prometheus-rpm/issues/400

Add blackbox exporter binary caps.

---

thanos/thanos.spec

Release notes:
https://github.com/thanos-io/thanos/releases/tag/v0.20.0

Upgrade Thanos to 0.20.0

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.20.1

Update Thanos to 0.20.1

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.26.1

Update Prometheus to 2.26.1

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.27.1

Update Prometheus to 2.27.1

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.20.2

Update Thanos to 0.20.2

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.21.0

Update Thanos to 0.21.0

---

thanos/thanos.spec

Release notes:
https://github.com/thanos-io/thanos/releases/tag/v0.21.1

Update Thanos to 0.21.1

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.28.1

Update Prometheus to 2.28.1

---

thanos/thanos.spec

Release notes:
https://github.com/thanos-io/thanos/releases/tag/v0.22.0

Update Thanos to 0.22.0

---

prometheus2/prometheus2.spec

Release notes:
https://github.com/prometheus/prometheus/releases/tag/v2.29.1

Update Prometheus to 2.29.1

---

mtail/mtail.spec

Fixes https://github.com/lest/prometheus-rpm/issues/484

Fix mtail package

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.23.0

Update Thanos to 0.23.0

---

prometheus2/prometheus2.spec

Release notes:
https://github.com/prometheus/prometheus/releases/tag/v2.30.1

Update Prometheus to 2.30.1

---

thanos/thanos.spec

Release notes:
https://github.com/thanos-io/thanos/releases/tag/v0.23.1

Update Thanos to 0.23.1

---

prometheus2/prometheus2.spec

Release notes:
https://github.com/prometheus/prometheus/releases/tag/v2.31.0

Update Prometheus to 2.31.0

---

prometheus2/prometheus2.spec

Release notes:
https://github.com/prometheus/prometheus/releases/tag/v2.31.2

Update Prometheus to 2.31.2

---

prometheus2/prometheus2.spec

Release notes:
https://github.com/prometheus/prometheus/releases/tag/v2.32.0

Update Prometheus to 2.32.0

---

prometheus2/prometheus2.spec

Release notes:
https://github.com/prometheus/prometheus/releases/tag/v2.32.1

Update Prometheus to 2.32.1

---

couchbase_exporter/couchbase_exporter.spec
jmx_exporter/jmx_exporter.spec
mtail/mtail.spec
ping_exporter/ping_exporter.spec
prometheus2/prometheus2.spec
rabbitmq_exporter/rabbitmq_exporter.spec
templates/spec.tpl
thanos/thanos.spec

Fixes #294.  Tested using my local build environment (F32 34 35).

Add systemd-rpm-macros in Fedora so it stops breaking upgrades.

---

prometheus2/prometheus2.spec

Bump Prometheus to 2.33.4

---

Makefile
templating.yaml

Add Squid exporter

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.25.0

Update Thanos to 0.25.0

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.33.5

Update Prometheus to 2.33.5

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.25.1

Update Thanos to 0.25.1

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.34.0

Update Prometheus to 2.34.0

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.25.2

Update Thanos to 0.25.2

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.26.0

Update Thanos to 0.26.0

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.36.2

Update Prometheus to 2.36.2

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.27.0

Update Thanos to 0.27.0

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.37.0

Update Prometheus to 2.37.0

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.28.0

Update Thanos to 0.28.0

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.39.0

Update Prometheus to 2.39.0

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.28.1

Update Thanos to 0.28.1

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.39.1

Update Prometheus to 2.39.1

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.40.1

Update Prometheus to 2.40.1

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.40.2

Update Prometheus to 2.40.2

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.40.3

Update Prometheus to 2.40.3

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.40.5

Update Prometheus to 2.40.5

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.40.7

Update Prometheus to 2.40.7

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.41.0

Update Prometheus to 2.41.0

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.30.1

Update Thanos to 0.30.1

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.30.2

Update Thanos to 0.30.2

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.43.0

Update Prometheus to 2.43.0

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.31.0

Update Thanos to 0.31.0

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.43.1

Update Prometheus to 2.43.1

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.44.0

Update Prometheus to 2.44.0

---

prometheus2/prometheus2.spec

Update Prometheus to 2.45.1

---

prometheus2/prometheus2.spec

Update Prometheus to 2.46.0

---

prometheus2/prometheus2.spec

Update Prometheus to 2.47.1

---

thanos/thanos.spec

Update Thanos to 0.32.4

---

templating.yaml

Resolves https://github.com/lest/prometheus-rpm/issues/756

Update SQL exporter to 0.12.3

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.47.2

Update Prometheus to 2.47.2

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.32.5

Update Thanos to 0.32.5

---

prometheus2/prometheus2.spec

Release notes:
https://github.com/prometheus/prometheus/releases/tag/v2.48.1

Update Prometheus to 2.48.1

---

bin/sign

Fixes https://github.com/lest/prometheus-rpm/issues/778
@lest, it would also require to reupload all RHEL9 RPMs to packagecloud.io, can you please do that?

Sign RHEL 8+ packages with SHA256

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.49.1

Update Prometheus to 2.49.1

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.33.0

Update Thanos to 0.33.0

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.34.1

Update Thanos to 0.34.1

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.51.0

Update Prometheus to 2.51.0

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.51.1

Update Prometheus to 2.51.1

---

thanos/thanos.spec

Release notes: https://github.com/thanos-io/thanos/releases/tag/v0.35.1

Update Thanos to 0.35.1

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.51.2

Update Prometheus to 2.51.2

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.52.0

Update Prometheus to 2.52.0

---

prometheus2/prometheus2.spec

Release notes: https://github.com/prometheus/prometheus/releases/tag/v2.53.0

Update Prometheus to 2.53.0
